### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by ghost** [alevicki/ionic-parse-starter#4]
Hello,

I am going through your guide but I am unable to successfully log-in after I create a User in my Parse account. I get the "An unexpected error has occurred, please try again." message when I test in my browser and I only get a spinning icon in my iOS emulator. Am I missing something in the documentation?

**Comment by ejwill** [comment]
same issue

**Comment by ghost** [comment]
I found my problem. My app.js file with my App ID and JS Key was not with the rest of my files. I must have copied it over to somewhere else and forgot to paste it back in with the rest of the files after inserting my Parse account information.

**Comment by alevicki** [comment]
@ejwill is your issue similar?

**Comment by ejwill** [comment]
@alevicki I'll take a look when I get home from work and let you know

**Comment by ejwill** [comment]
@alevicki the problem was that I did not have Parse send users email verification so I went and manually made them true and I was able to login after that.

**Comment by alevicki** [comment]
Closing this out.
